# Site settings
title: Korijn van Golen
email: korijn@gmail.com
baseurl: ""
url: "https://korijn.dev"
github_username:  korijn
linkedin_username:  korijn

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Theme settings
show_excerpts: true
